import 'package:hive_flutter/hive_flutter.dart';
import '../models/job_application.dart';

// ============================================
// WHAT IS THIS FILE?
// ============================================
// The DatabaseService is responsible for:
// 1. Initializing Hive (the local database)
// 2. Registering adapters (telling Hive how to store our models)
// 3. Opening boxes (like tables in a database)
// 4. Providing access to boxes throughout the app

class DatabaseService {
  // ============================================
  // SINGLETON PATTERN
  // ============================================
  // We only want ONE instance of DatabaseService in the entire app.
  // This prevents multiple database connections and ensures consistency.
  //
  // Usage: DatabaseService.instance.initialize()
  static final DatabaseService instance = DatabaseService._internal();

  // Private constructor - prevents creating new instances with DatabaseService()
  DatabaseService._internal();

  // ============================================
  // BOX NAMES (Constants)
  // ============================================
  // Box names are like table names in a database.
  // We store them as constants to avoid typos.
  static const String jobsBoxName = 'jobs';

  // ============================================
  // BOX REFERENCES
  // ============================================
  // After opening a box, we keep a reference to it for quick access.
  // The underscore (_) makes it private to this class.
  Box<JobApplication>? _jobsBox;

  // ============================================
  // GETTERS
  // ============================================
  // Public getter to access the jobs box from outside this class.
  // Throws an error if the database hasn't been initialized yet.
  Box<JobApplication> get jobsBox {
    if (_jobsBox == null || !_jobsBox!.isOpen) {
      throw Exception(
        'Database not initialized! Call DatabaseService.instance.initialize() first.',
      );
    }
    return _jobsBox!;
  }

  // ============================================
  // INITIALIZE METHOD
  // ============================================
  // This method MUST be called before using any database features.
  // It sets up Hive and opens all necessary boxes.
  //
  // Call this in main.dart before runApp():
  //   await DatabaseService.instance.initialize();
  Future<void> initialize() async {
    // Step 1: Initialize Hive for Flutter
    // This sets up the storage path on the device
    await Hive.initFlutter();

    // Step 2: Register adapters
    // Adapters tell Hive how to convert objects to bytes and back.
    // The adapter was auto-generated by hive_generator in job_application.g.dart
    if (!Hive.isAdapterRegistered(0)) {
      Hive.registerAdapter(JobApplicationAdapter());
    }

    // Step 3: Open boxes
    // A box is like a table that stores objects of a specific type.
    // openBox() creates the box if it doesn't exist, or opens it if it does.
    _jobsBox = await Hive.openBox<JobApplication>(jobsBoxName);
  }

  // ============================================
  // CLOSE METHOD
  // ============================================
  // Closes all boxes and Hive itself.
  // Call this when the app is closing (usually not needed).
  Future<void> close() async {
    await _jobsBox?.close();
    await Hive.close();
  }

  // ============================================
  // CLEAR ALL DATA
  // ============================================
  // Deletes all data from all boxes.
  // Useful for testing or "reset app" feature.
  // BE CAREFUL: This cannot be undone!
  Future<void> clearAll() async {
    await _jobsBox?.clear();
  }
}
